### ISSUE TITLE
'pnpm dev' failed

### ISSUE THREAD

**Issue by Randysheng** [Tresjs/lab#1]
When i run 'pnpm dev' locally, i get this error:

![image](https://user-images.githubusercontent.com/11868294/219247816-88ce3db0-0359-4455-887a-b804bfbd06bd.png)

I guess maybe **node version** cause? I checked the node version, and It's **16.19.0**. Ok, I change it to **18.14.0**. Yes，it works! Then , I change it to **17.9.1**, the error again.  

Add something about  **node version** in README?

**Comment by alvarosabu** [comment]
Hey @Randysheng thanks for the feedback, we could add it to the `package.json`, would you be interested in creating the PR? https://www.geeksforgeeks.org/how-to-define-the-required-node-js-version-in-package-json/

**Comment by Randysheng** [comment]
> Hey @Randysheng thanks for the feedback, we could add it to the `package.json`, would you be interested in creating the PR? https://www.geeksforgeeks.org/how-to-define-the-required-node-js-version-in-package-json/

Sure. I forget the `package.json`

**Comment by JaimeTorrealba** [comment]
Hi after the last commit 4-mar

I can run dev enviroment in my local, 

![image](https://user-images.githubusercontent.com/63722373/222901107-070a4477-3037-4b9c-a4f1-b0bc5592883d.png)

any solution?

BTW for some reason, just a few examples work in local an others don't
I know there's an issue for this but what could be?

**Comment by alvarosabu** [comment]
@JaimeTorrealba for that last one you see https://github.com/kidonng/unocss-preset-daisy/issues/12. 

If you pull the latest main should be fixed, as well as playgrounds that weren't working
