### ISSUE TITLE
lab.tresjs.org doesn't work (Only header is shown. Fail to fetch items.)

### ISSUE THREAD

**Issue by wonjinYi** [Tresjs/lab#145]
Hello. First of all I appreciate a lot for your effort to develop and maintain it.
I'm really happy to meet this awesome library.

# The Problem on `lab.tresjs.org`

I'm writing to notify the possibility that there are some wrong settings from server-side.

Today I tried to see the **ShowCase** page (lab.tresjs.org), but I can't do like the photo below.

![image](https://github.com/Tresjs/lab/assets/25413566/62fde472-5cb9-4ee5-9308-b9aa6f3023bf)

It fails to get belows according to console messages.
- https://lab.tresjs.org/
- https://lab.tresjs.org/api/_content/query/luVj25sCnR.1720210146607.json?_params=%7B%22where%22:%5B%7B%22_path%22:%22%2Fexperiments%2Fsimple-editor%22%7D%5D,%22first%22:true,%22sort%22:%5B%7B%22_stem%22:1,%22$numeric%22:true%7D%5D%7D

Specific links are also not working. (2 examples)
- https://lab.tresjs.org/experiments/simple-editor
- https://lab.tresjs.org/experiments/glass-material

# Local has no problems.

When I clone and run it at local environment, it works well.
![image](https://github.com/Tresjs/lab/assets/25413566/bb924704-882f-4ce8-b27e-142041f6d7fd)

Thank you.

**Comment by alvarosabu** [comment]
Should be working now  https://lab.tresjs.org/
