### ISSUE TITLE
Events were failed when dynamically add object3d to primitive!

### ISSUE THREAD

**Issue by fdkhb** [Tresjs/lab#157]
Hello. I have encountered with a problem with events of component 'primitive'.
### Problem
I initialize a primitive component to bond with an array as below:
![2024-08-06_162636](https://github.com/user-attachments/assets/13499f71-c875-4a01-bea5-0bb66f9520cd)

`
<script setup lang="ts">
const gl = {
  clearColor: '#12B7F3',
  shadows: true,
  alpha: false,
  shadowMapType: BasicShadowMap,
  outputColorSpace: SRGBColorSpace,
  toneMapping: NoToneMapping,
};
var testList = ref<Array<THREE.Object3D>>([])

onMounted(() => {

    const geometry2 = new THREE.ConeGeometry();
      const mtl2 = new THREE.MeshBasicMaterial({ color: 0x00ffff })
      const mesh2  = new THREE.Mesh(geometry2, mtl2)
      testList.value.push(mesh2)
})

const clickMethod = () => {
  const geometry1 = new THREE.ConeGeometry();
      const mtl1 = new THREE.MeshBasicMaterial({ color: 0xffff00 })
      const mesh1  = new THREE.Mesh(geometry1, mtl1 )
      testList.value.push(mesh1)

}
</script>
`
As result, the mesh2 created in OnMounted() can arise the 'pointer-enter' and 'click' events. But mesh1 created by clicking button failed to arise these two events. Eager to get your help.

**Comment by alvarosabu** [comment]
Hi @fdkhb this is not the correct place to open issues for Tres, please use https://github.com/Tresjs/tres/issues/new/choose
