### ISSUE TITLE
Two Warnings in Chrome when using gltf Model approach to load and run

### ISSUE THREAD

**Issue by thorstensson** [Tresjs/lab#214]
Hello

Thanks for the great work. Just started with Tres in Vue, and love it, but I'm getting the two below warnings in Chrome when loading and animating a gltf model, using  your approach here to load the model : https://docs.tresjs.org/cookbook/load-models.html#using-usegltf

**The Warnings:**

chunk-RZFXUODE.js?v=c85fe90a:33228 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

main.js:5 [Vue warn]: onUnmounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

The warnings vanish if I don't include my HeroBackgroundTres component (ok, have to come up with a better name for it)

**HeroBackgroundTres.vue code:**
```
<script setup lang="ts">
import { TresCanvas } from '@tresjs/core';
import Model from '@/model/Model.vue';
</script>

<template>
  <div class="tres-wrapper">
    <TresCanvas>
      <TresPerspectiveCamera :position="[-3, -2, 4]" />
      <Suspense>
        <Model />
      </Suspense>
      <TresDirectionalLight :intensity="2" />
      <TresAmbientLight :intensity="1" />
    </TresCanvas>
  </div>
</template>

<style lang="scss" scoped>
.tres-wrapper {
  position: absolute;
  top: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
</style>
```

**Model.vue**
```
<script setup lang="ts">
import { useTresContext } from '@tresjs/core'
import { useGLTF } from '@tresjs/cientos';
import { useLoop } from '@tresjs/core';
import { shallowRef } from 'vue';

const boxRef = shallowRef();
const context = useTresContext();
const path = './src/assets/gltf/scene.gltf';
const { scene, nodes, animations, materials } = await useGLTF(path, { draco: true });

const { onBeforeRender } = useLoop();

onBeforeRender(({ delta, elapsed }) => {
    if (boxRef.value) {
        boxRef.value.rotation.y += delta
        boxRef.value.rotation.z = elapsed * 0.2
    }
})

</script>

<template>
        <primitive :object="scene" ref="boxRef" />
</template>
```
Thankful for any insights as I get a slight rash from yellow warnings. Again, Tres is great, keep up the fine work 

.T 😎

**Comment by thorstensson** [comment]
Hmm

thinking out loud, and re-reading the onUnmount warning, it is the fact that I am lang=ts and using

`const { scene, nodes, animations, materials } = await useGLTF(path, { draco: true });`

Hmm, I'll see if I can work around that without having to fiddle with compiler settings,

T

**Comment by andretchen0** [comment]
Can confirm. Seeing the same using Tres 4.3.1. 

FF and Chrome.

**Comment by thorstensson** [comment]
Hi

I have now solved this, turned out I needed to do some reading up on Vue's <Suspence> component, and how to properly place it. Your Bunny code example also helped on the Doc pages. This ticket can be closed.

**Focusing only on the template, this worked fine**
```
**Parent component**
<template>
    <TresCanvas v-bind="gl">
        <TresPerspectiveCamera :position="[2, 2, 9]" :look-at="[0, 2, 0]" />
        <Levioso>
            <Suspense>
                <HeroBackgroundTres />
            </Suspense>
        </Levioso>
        <TresDirectionalLight color="#F78B3D" :position="[3, 3, 3]" :intensity="1" />
        <TresAmbientLight :intensity="2" />
    </TresCanvas>
    <div class="full">
        <NoiseBackgroundFx />
        <HeroScroller :speed="config.speed" :text="config.text"></HeroScroller>
    </div>
</template>
```
**HeroBackgroundTres**
```
<script setup lang="ts">
import { ref } from 'vue'
import { useAnimations, useGLTF } from '@tresjs/cientos'

const { scene: model, animations } = await useGLTF('./src/model/gltf/scene.gltf', {
  draco: true
})
</script>

<template>
  <primitive :object="model" />
</template>
```

Thanks, Thomas

**Comment by andretchen0** [comment]
Closing: User found a solution

**Comment by andretchen0** [comment]
@thorstensson

Thanks for following up with the conclusion!
